### RNN for Sentiment Analysis

In [86]:
import pandas as pd

In [87]:
df=pd.read_csv("IMDB Dataset.csv")

In [88]:
df.shape

(50000, 2)

In [89]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [90]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [91]:
df.drop_duplicates(inplace=True)

In [92]:
df.shape

(49582, 2)

### Text Preprocessing

## 1. Converting to lower case

In [93]:
df["review"]=df["review"].str.lower()

## 2. Removing the urls

In [94]:
import re

In [95]:
def remove_urls(text):
    text=re.sub(r"http\S+", "",text)  # pattern , replacement , string
    return text

In [96]:
df["review"]=df["review"].apply(remove_urls)

### 3. Remove Punctuations

In [97]:
def remove_punctuations(text):
    text=re.sub(r"[^A-Za-z0-9\s]","",text)
    return text

In [98]:
df["review"]=df["review"].apply(remove_punctuations)

### 4. Removing HTML

In [99]:
def remove_html(text):
    text=re.sub(r"<.*?>","",text)
    return text

In [100]:
df["review"]=df["review"].apply(remove_html)

### 5. Removing the Stopwords

In [101]:
import nltk

In [102]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [103]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [104]:
sample_text="I love to code in Python!"
tokens=word_tokenize(sample_text)

In [105]:
tokens

['I', 'love', 'to', 'code', 'in', 'Python', '!']

In [106]:
def remove_stopwords(text):
    tokens=word_tokenize(text)
    stop_words=stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text=text.replace(word, "")

    return text

In [107]:
df["review"]=df["review"].apply(remove_stopwords)

In [108]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive

### 6. Stemming

In [109]:
# running=>run
# playing=>play

In [110]:
from nltk.stem import PorterStemmer

In [111]:
def stemming(text):
    ps=PorterStemmer()
    stemmed_words=[]

    tokens=word_tokenize(text)
    for token in tokens:
        stemmed_tokens=ps.stem(token)
        stemmed_words.append(stemmed_tokens)

    return " ".join(stemmed_words)

In [112]:
df["review"]=df["review"].apply(stemming)

In [113]:
df.head()

                                              review sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1  wder ltle producti br br film techniqu unssum ...  positive
2  thought th wder wy spend tme o hot summer week...  positive
3  bsclli re fmli lttle boy jke thk re zomb close...  negative
4  petter mtte love time mey vulli stunng film wt...  positive

### 7. Encoding

In [114]:
from sklearn.preprocessing import LabelEncoder

In [115]:
le=LabelEncoder()

In [116]:
df["sentiment"]=le.fit_transform(df["sentiment"])

In [117]:
y=df["sentiment"]

In [118]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

### 8. Vectorization

In [119]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [120]:
tf=TfidfVectorizer(max_features=5000)

X=tf.fit_transform(df["review"])

In [121]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057140 stored elements and shape (49582, 5000)>

In [122]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057140 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3538)	0.05515484681268887
  (0, 2868)	0.09361182809242374
  (0, 4940)	0.11467310366614668
  (0, 3002)	0.47200539890110405
  (0, 1275)	0.1357698919196183
  (0, 2289)	0.049500237517476293
  (0, 1933)	0.0791260308382
  (0, 3550)	0.0963974330192639
  (0, 1362)	0.06162489377343992
  (0, 1963)	0.061560444992697486
  (0, 219)	0.08588920995304898
  (0, 1620)	0.0738170550485134
  (0, 4369)	0.041994187696759305
  (0, 4171)	0.17799685402440263
  (0, 3693)	0.033532198172897175
  (0, 4737)	0.26798942924092045
  (0, 3805)	0.04427609784380831
  (0, 4769)	0.05877405881441711
  (0, 1739)	0.037520883911174724
  (0, 4497)	0.07614066339174266
  (0, 3857)	0.17537900435282314
  (0, 1630)	0.06142445471882175
  (0, 1862)	0.07433134577032253
  (0, 3329)	0.06406818508428483
  (0, 3332)	0.0844754682576354
  :	:
  (49581, 4890)	0.10682334916138103
  (49581, 1542)	0.17584072573791829
  (49581, 4494)	0.09410069396961679
  (49581, 434)	0.11251655954741112
  (49581, 4277)	0.10905956327445408
  (49581, 1958)	0.0999074542943991
  (49581, 555)	0.08424218838425554
  (49581, 2187)	0.14180348667063264
  (49581, 2217)	0.09535602544797335
  (49581, 4347)	0.17508214877875983
  (49581, 4629)	0.1157123083349983
  (49581, 3647)	0.087334023293812
  (49581, 4734)	0.12354122837064464
  (49581, 1977)	0.1279546327938257
  (49581, 527)	0.1247934452922504
  (49581, 2621)	0.17341357547872566
  (49581, 4458)	0.16002233459530202
  (49581, 2174)	0.18983797727912208
  (49581, 4033)	0.20100044911463438
  (49581, 341)	0.14784964476913964
  (49581, 2695)	0.1740080872946952
  (49581, 439)	0.13323526536564564
  (49581, 4980)	0.15095820717373318
  (49581, 1764)	0.15815315432712562
  (49581, 3489)	0.1519741559925848

### Dataset and DataLoader

In [123]:
from sklearn.model_selection import train_test_split

In [124]:
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [125]:
X_train.shape

(39665, 5000)

In [126]:
X_test.shape

(9917, 5000)

In [127]:
from torch.utils.data import TensorDataset, DataLoader

In [130]:
import numpy
import torch

In [129]:
X_train=X_train.toarray()
X_test=X_test.toarray()

In [131]:
trainset=TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
)
testset=TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

C:\Users\HP\AppData\Local\Temp\ipykernel_15088\1809038279.py:3: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:219.)
  torch.from_numpy(y_train.values).float()

In [132]:
trainloader=DataLoader(trainset,batch_size=64,shuffle=True)
testloader=DataLoader(testset,batch_size=64,shuffle=True)

### Build our RNN

In [139]:
import torch.nn as nn
import torch.optim as optim

In [144]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()

        self.hidden_size=hidden_size
        self.num_layers=num_layers

        # RNN layer
        self.rnn=nn.RNN(input_size,hidden_size,num_layers,batch_first=True)

        # fully connected layer 
        self.fc=nn.Linear(hidden_size,1)

        # This architecture is => many to one 

    def forward(self,x):
        # optional step 

        h0= torch.zeros(self.num_layers,x.size(0),self.hidden_size)

        out,_=self.rnn(x,h0)
        # 1st =>hidden state of all timestamp=>(batch_size,seq_len,hidden_size)
        # 2nd =>final hidden state of all last timestamp

        out=self.fc(out[:,-1,:])
        return out

In [145]:
input_size=X_train.shape[1]

model=RNN(input_size)

criteria=nn.BCELoss()

optimizer=optim.Adam(model.parameters())

### Training the Model

In [148]:
import torch

In [147]:
# unsqueeze => Adds one dimension to data
# squeeze => Removes one dimension from data

In [152]:
epochs=10

for epoch in range(epochs):
    model.train()

    for xb,yb in trainloader:

        optimizer.zero_grad()

        xb=xb.unsqueeze(1) # add singleton direction

        outputs=model(xb) # (batch_size,1)

        outputs=torch.sigmoid(outputs.squeeze()) # (batch_size,)=>probability

        loss=criteria(outputs,yb)  # compute loss

        loss.backward()

        optimizer.step()

    print(f"{epoch}/{epochs}, and loss={loss.item()}")

0/10, and loss=0.2787994146347046
1/10, and loss=0.1733485460281372
2/10, and loss=0.29640188813209534
3/10, and loss=0.1577267348766327
4/10, and loss=0.41753286123275757
5/10, and loss=0.2592003345489502
6/10, and loss=0.41114553809165955
7/10, and loss=0.18266957998275757
8/10, and loss=0.24517051875591278
9/10, and loss=0.2821579575538635

### Evaluate

In [155]:
model.eval()

with torch.no_grad():
    correct=0
    total=0

    for xb,yb in testloader:

        xb=xb.unsqueeze(1)

        outputs=model(xb)

        predicted=(torch.sigmoid(outputs.squeeze())>0.5).float()


        total+=yb.size(0)

        correct+=(predicted==yb).sum().item()

In [156]:
print("Accuracy =>",correct/total)

Accuracy => 0.8565090249067259