In [1]:
import pandas as pd 
from transformers import T5Tokenizer, Trainer, TrainingArguments, T5ForConditionalGeneration

In [4]:
train_data=pd.read_csv("samsum-train.csv")
val_data=pd.read_csv("samsum-validation.csv")

In [5]:
train_data.head()

,id,dialogue,summary
0,13818513,Amanda: I baked cookies. Do you want some?\r\...,Amanda baked cookies and will bring Jerry some...
1,13728867,Olivia: Who are you voting for in this electio...,Olivia and Olivier are voting for liberals in ...
2,13681000,"Tim: Hi, what's up?\r\nKim: Bad mood tbh, I wa...",Kim may try the pomodoro technique recommended...
3,13730747,"Edward: Rachel, I think I'm in ove with Bella....",Edward thinks he is in love with Bella. Rachel...
4,13728094,Sam: hey overheard rick say something\r\nSam:...,"Sam is confused, because he overheard Rick com..."

In [6]:
train_data.sample(6)

,id,dialogue,summary
7542,13814644,"Caleb: <file_other>\r\nGracie: haha, I've alre...",Gracie's grandparents are coming to dinner tom...
10344,13729669-1,Veronika: hey idk if iv ever mentioned that bu...,Veronika is working on a radio material about ...
1315,13821741,Jhordan: Hey \r\nJhordan: Anyone liked tacos c...,"Ewa, Mason and Jhordan attended tacos concert ..."
9600,13680335,"Jayden: Hi, we're coming to Florida next month...","Jayden is coming to Florida next month, probab..."
14063,13680212,Nadine: <file_photo>\r\nNadine: Shar Peis\r\nD...,Nadine owns two Shar peis. Donna owns a Staffo...
11984,13681592,Tony: i will be late tomorrow\r\nTony: perhaps...,Tony and Lisa were supposed to meet tomorrow a...

In [7]:
train_data.shape

(14732, 3)

In [8]:
val_data.shape

(818, 3)

In [10]:
# random sampling 
train_data=train_data.sample(4000,random_state=42).reset_index(drop=True)
val_data=val_data.sample(500,random_state=42).reset_index(drop=True)

In [12]:
train_data.shape
val_data.shape

(500, 3)

### Data Preprocessing

In [15]:
import re

In [19]:
def clean_data(text):
    text=re.sub(r"\r\n"," ",text) # lines
    text=re.sub(r"\s+", " ",text) # Spaces
    text=re.sub(r"<.*?>"," ",text) # html tags 
    text.strip()
    text.lower()
    return text

In [20]:
train_data["dialogue"]=train_data["dialogue"].apply(clean_data)
train_data["summary"]=train_data["summary"].apply(clean_data)

val_data["dialogue"]=val_data["dialogue"].apply(clean_data)
val_data["summary"]=val_data["summary"].apply(clean_data)

In [21]:
train_data["dialogue"][0]

"Violet: hi! i came across this Austin's article and i thought that you might find it interesting Violet:   Claire: Hi! :) Thanks, but I've already read it. :) Claire: But thanks for thinking about me :)"